// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rgb_mux,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.740000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=106,HLS_SYN_LUT=89}" *)

module rgb_mux (
        ap_clk,
        ap_rst_n,
        video_in_stream_TDATA,
        video_in_stream_TVALID,
        video_in_stream_TREADY,
        video_in_stream_TUSER,
        video_in_stream_TLAST,
        video_out_stream_TDATA,
        video_out_stream_TVALID,
        video_out_stream_TREADY,
        video_out_stream_TUSER,
        video_out_stream_TLAST,
        mux_V
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm0_0 = 1'b1;
parameter    ap_ST_st2_fsm1_1 = 2'b10;
parameter    ap_ST_st3_fsm2_1 = 2'b10;
parameter    ap_ST_st0_fsm1_0 = 2'b1;
parameter    ap_ST_st0_fsm2_0 = 2'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst_n;
input  [23:0] video_in_stream_TDATA;
input   video_in_stream_TVALID;
output   video_in_stream_TREADY;
input   video_in_stream_TUSER;
input   video_in_stream_TLAST;
output  [23:0] video_out_stream_TDATA;
output   video_out_stream_TVALID;
input   video_out_stream_TREADY;
output   video_out_stream_TUSER;
output   video_out_stream_TLAST;
input  [1:0] mux_V;

reg video_in_stream_TREADY;
reg video_out_stream_TVALID;
reg    ap_rst_n_inv;
reg   [23:0] video_in_stream_data_V_tmp_reg_212;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm0 = 1'b1;
reg    ap_sig_cseq_ST_st1_fsm0_0;
reg    ap_sig_bdd_35;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm1 = 2'b1;
reg    ap_sig_cseq_ST_st2_fsm1_1;
reg    ap_sig_bdd_51;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm2 = 2'b1;
reg    ap_sig_ioackin_video_out_stream_TREADY;
reg    ap_sig_cseq_ST_st3_fsm2_1;
reg    ap_sig_bdd_66;
reg   [23:0] ap_reg_ppstg_video_in_stream_data_V_tmp_reg_212_pp0_it1;
reg   [0:0] video_out_stream_tuser_tmp_reg_218;
reg   [0:0] ap_reg_ppstg_video_out_stream_tuser_tmp_reg_218_pp0_it1;
reg   [0:0] video_out_stream_tlast_tmp_reg_223;
reg   [0:0] ap_reg_ppstg_video_out_stream_tlast_tmp_reg_223_pp0_it1;
wire   [7:0] R_fu_105_p1;
reg   [7:0] R_reg_228;
reg   [7:0] ap_reg_ppstg_R_reg_228_pp0_it1;
reg   [7:0] G_reg_234;
reg   [7:0] ap_reg_ppstg_G_reg_234_pp0_it1;
reg   [7:0] B_reg_240;
reg   [7:0] ap_reg_ppstg_B_reg_240_pp0_it1;
wire   [0:0] tmp_2_fu_129_p2;
wire   [0:0] tmp_9_fu_135_p2;
wire   [0:0] tmp_s_fu_141_p2;
wire   [0:0] sel_tmp6_demorgan_fu_147_p2;
wire   [0:0] sel_tmp2_fu_158_p2;
wire   [0:0] sel_tmp7_fu_168_p2;
wire   [0:0] empty_read_fu_70_p4_1;
wire   [0:0] empty_read_fu_70_p4_2;
reg    ap_reg_ioackin_video_out_stream_TREADY = 1'b0;
wire   [0:0] sel_tmp1_fu_153_p2;
wire   [0:0] sel_tmp6_fu_163_p2;
wire   [23:0] p_1_fu_180_p4;
wire   [23:0] p_s_fu_173_p4;
wire   [0:0] or_cond_fu_193_p2;
wire   [23:0] newSel_fu_187_p3;
wire   [23:0] newSel9_fu_197_p3;
reg   [0:0] ap_NS_fsm0;
reg   [1:0] ap_NS_fsm1;
reg   [1:0] ap_NS_fsm2;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm0
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm0 <= ap_ST_st1_fsm0_0;
    end else begin
        ap_CS_fsm0 <= ap_NS_fsm0;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm1
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm1 <= ap_ST_st0_fsm1_0;
    end else begin
        ap_CS_fsm1 <= ap_NS_fsm1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm2
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm2 <= ap_ST_st0_fsm2_0;
    end else begin
        ap_CS_fsm2 <= ap_NS_fsm2;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ioackin_video_out_stream_TREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_video_out_stream_TREADY <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1) & ~(ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY))) begin
            ap_reg_ioackin_video_out_stream_TREADY <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1) & (ap_const_logic_1 == video_out_stream_TREADY))) begin
            ap_reg_ioackin_video_out_stream_TREADY <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((video_in_stream_TVALID == ap_const_logic_0) | ((ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1))))) begin
        B_reg_240 <= {{video_in_stream_TDATA[ap_const_lv32_17 : ap_const_lv32_10]}};
        G_reg_234 <= {{video_in_stream_TDATA[ap_const_lv32_F : ap_const_lv32_8]}};
        R_reg_228 <= R_fu_105_p1;
        video_in_stream_data_V_tmp_reg_212 <= video_in_stream_TDATA;
        video_out_stream_tlast_tmp_reg_223 <= empty_read_fu_70_p4_2;
        video_out_stream_tuser_tmp_reg_218 <= empty_read_fu_70_p4_1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1)))) begin
        ap_reg_ppstg_B_reg_240_pp0_it1 <= B_reg_240;
        ap_reg_ppstg_G_reg_234_pp0_it1 <= G_reg_234;
        ap_reg_ppstg_R_reg_228_pp0_it1 <= R_reg_228;
        ap_reg_ppstg_video_in_stream_data_V_tmp_reg_212_pp0_it1 <= video_in_stream_data_V_tmp_reg_212;
        ap_reg_ppstg_video_out_stream_tlast_tmp_reg_223_pp0_it1 <= video_out_stream_tlast_tmp_reg_223;
        ap_reg_ppstg_video_out_stream_tuser_tmp_reg_218_pp0_it1 <= video_out_stream_tuser_tmp_reg_218;
    end
end

always @ (ap_sig_bdd_35) begin
    if (ap_sig_bdd_35) begin
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_51) begin
    if (ap_sig_bdd_51) begin
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_66) begin
    if (ap_sig_bdd_66) begin
        ap_sig_cseq_ST_st3_fsm2_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm2_1 = ap_const_logic_0;
    end
end

always @ (video_out_stream_TREADY or ap_reg_ioackin_video_out_stream_TREADY) begin
    if ((ap_const_logic_0 == ap_reg_ioackin_video_out_stream_TREADY)) begin
        ap_sig_ioackin_video_out_stream_TREADY = video_out_stream_TREADY;
    end else begin
        ap_sig_ioackin_video_out_stream_TREADY = ap_const_logic_1;
    end
end

always @ (video_in_stream_TVALID or ap_sig_cseq_ST_st1_fsm0_0 or ap_sig_ioackin_video_out_stream_TREADY or ap_sig_cseq_ST_st3_fsm2_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((video_in_stream_TVALID == ap_const_logic_0) | ((ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1))))) begin
        video_in_stream_TREADY = ap_const_logic_1;
    end else begin
        video_in_stream_TREADY = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st3_fsm2_1 or ap_reg_ioackin_video_out_stream_TREADY) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1) & (ap_const_logic_0 == ap_reg_ioackin_video_out_stream_TREADY))) begin
        video_out_stream_TVALID = ap_const_logic_1;
    end else begin
        video_out_stream_TVALID = ap_const_logic_0;
    end
end
always @ (video_in_stream_TVALID or ap_CS_fsm0 or ap_sig_ioackin_video_out_stream_TREADY or ap_sig_cseq_ST_st3_fsm2_1) begin
    case (ap_CS_fsm0)
        ap_ST_st1_fsm0_0 : 
        begin
            ap_NS_fsm0 = ap_ST_st1_fsm0_0;
        end
        default : 
        begin
            ap_NS_fsm0 = 'bx;
        end
    endcase
end

always @ (ap_sig_cseq_ST_st2_fsm1_1 or ap_CS_fsm2 or ap_sig_ioackin_video_out_stream_TREADY or ap_sig_cseq_ST_st3_fsm2_1) begin
    case (ap_CS_fsm2)
        ap_ST_st3_fsm2_1 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~(ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY))) begin
                ap_NS_fsm2 = ap_ST_st3_fsm2_1;
            end else if ((~(ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & ~(ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) begin
                ap_NS_fsm2 = ap_ST_st0_fsm2_0;
            end else begin
                ap_NS_fsm2 = ap_ST_st3_fsm2_1;
            end
        end
        ap_ST_st0_fsm2_0 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1)))) begin
                ap_NS_fsm2 = ap_ST_st3_fsm2_1;
            end else begin
                ap_NS_fsm2 = ap_ST_st0_fsm2_0;
            end
        end
        default : 
        begin
            ap_NS_fsm2 = 'bx;
        end
    endcase
end

always @ (video_in_stream_TVALID or ap_sig_cseq_ST_st1_fsm0_0 or ap_CS_fsm1 or ap_sig_ioackin_video_out_stream_TREADY or ap_sig_cseq_ST_st3_fsm2_1) begin
    case (ap_CS_fsm1)
        ap_ST_st2_fsm1_1 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1)) & ~(video_in_stream_TVALID == ap_const_logic_0))) begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end else if ((~((ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1)) & (~(ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (video_in_stream_TVALID == ap_const_logic_0))))) begin
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            end else begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end
        end
        ap_ST_st0_fsm1_0 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((video_in_stream_TVALID == ap_const_logic_0) | ((ap_const_logic_0 == ap_sig_ioackin_video_out_stream_TREADY) & (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm2_1))))) begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end else begin
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            end
        end
        default : 
        begin
            ap_NS_fsm1 = 'bx;
        end
    endcase
end


assign R_fu_105_p1 = video_in_stream_TDATA[7:0];


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end


always @ (ap_CS_fsm0) begin
    ap_sig_bdd_35 = (ap_CS_fsm0[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm1) begin
    ap_sig_bdd_51 = (ap_const_lv1_1 == ap_CS_fsm1[ap_const_lv32_1]);
end


always @ (ap_CS_fsm2) begin
    ap_sig_bdd_66 = (ap_const_lv1_1 == ap_CS_fsm2[ap_const_lv32_1]);
end

assign empty_read_fu_70_p4_1 = video_in_stream_TUSER;

assign empty_read_fu_70_p4_2 = video_in_stream_TLAST;

assign newSel9_fu_197_p3 = ((tmp_2_fu_129_p2[0:0] === 1'b1) ? p_s_fu_173_p4 : ap_reg_ppstg_video_in_stream_data_V_tmp_reg_212_pp0_it1);

assign newSel_fu_187_p3 = ((sel_tmp7_fu_168_p2[0:0] === 1'b1) ? ap_reg_ppstg_video_in_stream_data_V_tmp_reg_212_pp0_it1 : p_1_fu_180_p4);

assign or_cond_fu_193_p2 = (sel_tmp7_fu_168_p2 | sel_tmp2_fu_158_p2);

assign p_1_fu_180_p4 = {{{ap_reg_ppstg_G_reg_234_pp0_it1}, {ap_reg_ppstg_B_reg_240_pp0_it1}}, {ap_reg_ppstg_R_reg_228_pp0_it1}};

assign p_s_fu_173_p4 = {{{ap_reg_ppstg_B_reg_240_pp0_it1}, {ap_reg_ppstg_R_reg_228_pp0_it1}}, {ap_reg_ppstg_G_reg_234_pp0_it1}};

assign sel_tmp1_fu_153_p2 = (tmp_2_fu_129_p2 ^ ap_const_lv1_1);

assign sel_tmp2_fu_158_p2 = (tmp_9_fu_135_p2 & sel_tmp1_fu_153_p2);

assign sel_tmp6_demorgan_fu_147_p2 = (tmp_2_fu_129_p2 | tmp_9_fu_135_p2);

assign sel_tmp6_fu_163_p2 = (sel_tmp6_demorgan_fu_147_p2 ^ ap_const_lv1_1);

assign sel_tmp7_fu_168_p2 = (tmp_s_fu_141_p2 & sel_tmp6_fu_163_p2);

assign tmp_2_fu_129_p2 = (mux_V == ap_const_lv2_1? 1'b1: 1'b0);

assign tmp_9_fu_135_p2 = (mux_V == ap_const_lv2_2? 1'b1: 1'b0);

assign tmp_s_fu_141_p2 = (mux_V == ap_const_lv2_3? 1'b1: 1'b0);

assign video_out_stream_TDATA = ((or_cond_fu_193_p2[0:0] === 1'b1) ? newSel_fu_187_p3 : newSel9_fu_197_p3);

assign video_out_stream_TLAST = ap_reg_ppstg_video_out_stream_tlast_tmp_reg_223_pp0_it1;

assign video_out_stream_TUSER = ap_reg_ppstg_video_out_stream_tuser_tmp_reg_218_pp0_it1;


endmodule //rgb_mux

